### ISSUE TITLE
Need more explanation on dependent wavefront execution

### ISSUE THREAD

**Issue by Yougmark** [RadeonOpenCompute/ROCm_Documentation#10]
https://github.com/RadeonOpenCompute/ROCm_Documentation/blob/e332bdb531c37c5837d37391d36ff3613e49da3d/Programming_Guides/Opencl-programming-guide.rst#L1111

In which case wavefronts can be dependent?  Isn't every work-items suggested to be independent?

When wavefronts are dependent, what does this paragraph means by saying "independent operations from different wavefronts can be selected to be assigned to a single vector unit to be executed in parallel every cycle."?

Thanks,

**Comment by axeldavy** [comment]
Hi,

I'm not an AMD dev, but I saw this unanswered. Here is my answer:

"If operations within a wavefront include dependencies" -> the sentence doesn't mean that there are 'dependent wavefronts' but that the sequential operations a wavefront has to execute (serially) have dependencies.
However operations picked from different wavefronts are independent.
Which is why the hardware can pick from several different wavefronts operations of different types and execute them in parallel.

If your program is mostly VALU instructions, that means basically non-VALU instructions (global memory access, integer computation common to the whole wavefront, constant load, lds access, etc) are free, as they are likely to be executed for free while a VALU operation is executed from another wavefront. That requires however a good occupancy, in order to have several wavefronts to pick from.

**Comment by jlgreathouse** [comment]
I apologize for not finding this question earlier -- I suppose I should follow more ROCm GitHub repos so I can see when these things come in.

@axeldavy is essentially correct. The phase "If operations within a wavefront include dependencies..." means "if a second instruction within a wavefront relies on a first instruction, and the result of the first instruction is not yet ready, that wavefront will not be scheduled again at least until the result is ready. Other wavefronts within that vector unit can be scheduled, however, to allow the hardware to continue executing instructions that are useful to the program."

In my opinion, if you're coming from the CPU world, you should think of a wavefront as a thread. The work-items are lanes of a vector within that thread. A GCN wavefront is a 64-wide vector operation, though sometimes that wavefront (that thread) can have scalar operations. In the CPU world, you might think of this as vector instructions like SSE and scalar instructions like normal x86 ops.

So, while you are correct that OpenCL doesn't necessarily make it easy to have work-items (or lanes of the vector) communicating with one another, the wavefront (thread) itself can reach an instruction that relies on data from a previous cycle. The simplest case may be doing a vector load from global memory followed by a vector add that relies on that data. The data must return from memory (which could take many hundreds of cycles) before it can use it in an arithmetic operation, so that wavefront will stall because operations within that wavefront include dependencies that are not yet met.

(In actuality, GCN will only stall on global memory loads once you hit an `s_waitcnt vmcnt()` operation. This allows wavefronts to create memory-level parallelism without complex data dependency tracking hardware.)

Other operations besides memory may cause delays, however, that stall a wavefront. For example, 32-bit integer multiplies (such as `v_mul_lo_u32`) may take more cycles than 24-bit integer multiplies (such as `v_mul_u32_u24`). As such, if you have an instruction immediately following a 32-bit integer multiply that relies on its result, that wavefront cannot be scheduled by the hardware the very next issue cycle. If there are other ready wavefronts, they will be run instead.

Processors like GCN GPUs could be considered [fine-grained multithreaded](https://en.wikipedia.org/wiki/Simultaneous_multithreading#Taxonomy) [vector processors](https://en.wikipedia.org/wiki/Vector_processor). Each cycle, each GCN compute unit can decide to run work from different thread (wavefront) in order to hide latency.

**Comment by jlgreathouse** [comment]
As an aside, it is also possible to have dependencies between wavefronts. In particular, if multiple wavefronts are part of the same workgroup, operations like `barrier(CLK_LOCAL_MEM_FENCE)` will cause a wavefront to stall until all of the others wavefronts in that workgroup _also_ reach that barrier.

While a wavefront is waiting in the resulting `s_barrier` instruction, the GCN CU will not schedule that wavefront again until all other wavefronts in that workgroup (which are required to be on the same CU, but not in the same vector unit within that CU) reach the barrier.

While those wavefronts are unable to be scheduled, other wavefronts assigned to this CU may be scheduled. These wavefronts could be from the same workgroup (as it is possible to have up to 16 waves within a single workgroup spread over the CU's 4 vector units), different workgroups (as we may have up to 16 workgroups scheduled on the same CU), or even from different kernels and/or processes (as GCN allows multiple kernels to be simultaneously in flight, and those kernels can be from different virtual memory spaces).

**Comment by Yougmark** [comment]
Very well explained.  Thanks a lot!!
